name: test
on:
  - push
  - pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Configure Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ matrix.node-version }}-${{ runner.OS }}-build-${{ hashFiles('package.json') }}
      - name: Install npm in version ${{ matrix.node-version }}
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Run test in version ${{ matrix.node-version }}
        run: npm run test
        env:
          CI: true
      - name: Verify if gh exists
        run: gh --version
      - name: Publish on NPM
        uses: mikeal/merge-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Create release
        # env:
        #   GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          RELEASE_TAG=`git describe --tags`
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh release create ${RELEASE_TAG} --title "${RELEASE_TAG}"
